### ISSUE TITLE
Updates needed for Bonsai

### ISSUE THREAD

**Issue by asachs01** [target/sensu-go-goalert#1]
Hi Goalert folks! Aaron here from Sensu 👋 . Adam came and talked during Sensu Summit about Goalert and the Goalert Sensu Handler. Would y'all be open to uploading the handler to [Bonsai](https://bonsai.sensu.io) where the handler could be used as an asset? I'd be happy to contribute the needed changes if you're open to it.

**Comment by m17ch** [comment]
Hi @asachs01 -- absolutely we're interested in getting the handler in Bonsai!  Getting the handler code open sourced was the first priority with the follow-up objective being the Bonsai config bits.  We'd be happy to accept a PR for it or coordinate efforts with you (whatever works)!  Thanks.

**Comment by asachs01** [comment]
Awesome! What are y'all doing for CI stuff right now? Most of the assets use Travis + Goreleaser. Would that work for y'all?

**Comment by m17ch** [comment]
We don't have any experience using Travis or GoReleaser, but those should work just fine if they're free + easy to set up.

**Comment by m17ch** [comment]
Thanks again for your help on this, @asachs01 -- I've finalized all config requirements & confirmed everything appears to be working as desired for Bonsai asset publication.  I've also validated that I'm able to pull/config the assets on my test Sensu Go servers and performed a functional integration test with GoAlert.

Let me know if you notice anything awry (feel free to re-open if you notice any outstanding items).
